
export const autoCompleteTextActionTypes={
REQUEST_USERS_PENDING :"REQUEST_USERS_PENDING",
REQUEST_USERS_SUCCESS :"REQUEST_USERS_SUCCESS",
REQUEST_USERS_FAILED : "REQUEST_USERS_FAILED",
HANDLE_CHANGE: "HANDLE_CHANGE",
SET_USER_NAME: "SET_USER_NAME",
}